services:
  traefik:
    image: "traefik:v2.11"
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`traefik.environment`,`local`)"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  portfolio:
    build: 
      context: .
      dockerfile: "docker/Dockerfile.portfolio"
      target: "development"
    image: "guy-romelle-magayano:portfolio"
    command: "nx run portfolio:dev"
    volumes:
      - "client:/app"
      - "node-data:/app/node_modules"
      - "next-data:/app/.next"
      - "public-data:/app/public"
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.local`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
      - "traefik.environment=local"
    depends_on:
      - traefik

volumes:
  node-data:
    driver: local
  next-data:
    driver: local
  public-data:
    driver: local
