[build]
  command = "CI=false yarn build"
  publish = ".next"

  [build.environment]
    NETLIFY_USE_YARN = "true"
    NODE_VERSION = "18.4.0"
    YARN_VERSION = "1.22.19"
    YARN_FLAGS = "--pure-lockfile --ignore-engines"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
	package = "@netlify/plugin-lighthouse"
