name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn set version classic
        working-directory: ./

      - run: yarn install
        working-directory: ./


      - uses: nrwl/nx-set-shas@v4

      - run: git branch --track main origin/main
        if: ${{ github.event_name == 'pull_request' }}

      - run: git branch --track main origin/main
        if: ${{ github.event_name == 'pull_request' }}

      - run: yarn nx-cloud record -- nx format:check
        working-directory: ./


      - run: yarn nx affected -t lint test build e2e-ci
        working-directory: ./
